{
 "title": "Client Usage Model Dashboard",
 "tags": [ "model: client" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "throughput_unit_rate", "query": 0.1 },
   { "name": "partition_unit_rate", "query": 0.05 },
   { "name": "storage_unit_rate", "query": 0.001 },
   { "name": "throughput_in_unit_rate", "query": 0.15 },
   { "name": "throughput_out_unit_rate", "query": 0.05 },
   { "name": "throughput_tps", "query": 1000 },
   { "name": "storage", "query": 100000000 },
   { "name": "partitions_max", "query": 1000 },
   { "name": "total_costs", "query": 5000 },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "chargecode",
    "label": "Chargecode",
    "query": {
     "query": "label_values(kafka_server_produce_byte_rate{cluster=\"${cluster}\"},chargecode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$total_costs", "type": "math" }
   ]
  },
  {
   "title": "Total Client Usage Bill",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$dash_producer_bill_rate + $dash_consumer_bill_rate",
     "type": "math"
    }
   ]
  },
  {
   "title": "Profit/Loss Value",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($dash_producer_bill_rate + $dash_consumer_bill_rate) - $total_costs",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(($throughput_utilization + $partition_utilization + $storage_utilization) / 3) * 100",
     "type": "math"
    }
   ]
  },
  { "title": "Chargecode Wise Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Chargecode Wise Usage - Client Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_server_produce_byte_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode) * $throughput_in_unit_rate + sum(avg_over_time(kafka_server_fetch_byte_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode) * $throughput_out_unit_rate"
    }
   ]
  },
  {
   "title": "Chargecode Wise Usage - Client Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_server_produce_byte_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode) * $throughput_in_unit_rate + sum(avg_over_time(kafka_server_fetch_byte_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode) * $throughput_out_unit_rate"
    }
   ]
  },
  {
   "title": "Top 5 Clients per Chargecode",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, sum((avg_over_time(kafka_server_produce_byte_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}[$__range]) * $throughput_in_unit_rate) or (avg_over_time(kafka_server_fetch_byte_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}[$__range]) * $throughput_out_unit_rate)) by (client_id))"
    }
   ]
  },
  { "title": "Client Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Producer Throughput Usage Bill",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(kafka_server_produce_byte_rate{cluster=\"$cluster\", chargecode=~\"$chargecode\"}[$__range])) by (chargecode)) * $throughput_in_unit_rate"
    }
   ]
  },
  {
   "title": "Produce Byte Rate",
   "type": "timeseries",
   "description": "Indicates the data produce rate of the client in bytes/sec",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_server_produce_byte_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Throughput Usage Bill",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(kafka_server_fetch_byte_rate{cluster=\"$cluster\", chargecode=~\"$chargecode\"}[$__range])) by (chargecode)) * $throughput_out_unit_rate"
    }
   ]
  },
  {
   "title": "Consumer Byte Rate",
   "type": "timeseries",
   "description": "Indicates the data consumption rate of the client in bytes/sec",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_server_fetch_byte_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}