{
 "title": "Cost Centre Model Dashboard",
 "tags": [ "model: cost" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "throughput_unit_rate", "query": 0.1 },
   { "name": "partition_unit_rate", "query": 0.05 },
   { "name": "storage_unit_rate", "query": 0.001 },
   { "name": "throughput_in_unit_rate", "query": 0.15 },
   { "name": "throughput_out_unit_rate", "query": 0.05 },
   { "name": "throughput_tps", "query": 1000 },
   { "name": "storage", "query": 100000000 },
   { "name": "partitions_max", "query": 1000 },
   { "name": "total_costs", "query": 5000 },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "chargecode",
    "label": "Chargecode",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_bytesinpersec{cluster=\"${cluster}\"},chargecode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$total_costs", "type": "math" }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(($throughput_utilization + $partition_utilization + $storage_utilization) / 3) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Chargecode Wise Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Chargecode Wise Usage - Cost Centre",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(((sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode)) * $throughput_unit_rate + (count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $partition_unit_rate + (sum(kafka_log_log_size{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $storage_unit_rate) / (scalar((sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range]))) * $throughput_unit_rate + (count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode!=\"\"})) * $partition_unit_rate + (sum(kafka_log_log_size{cluster=\"$cluster\",chargecode!=\"\"})) * $storage_unit_rate))) * $total_costs"
    }
   ]
  },
  {
   "title": "Chargecode wise Cost Split percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode)) * $throughput_unit_rate + (count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $partition_unit_rate + (sum(kafka_log_log_size{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $storage_unit_rate) / (scalar((sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range]))) * $throughput_unit_rate + (count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode!=\"\"})) * $partition_unit_rate + (sum(kafka_log_log_size{cluster=\"$cluster\",chargecode!=\"\"})) * $storage_unit_rate))) * $total_costs"
    }
   ]
  },
  {
   "title": "Top 5 Chargecodes based on Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Top 5 Chargecode based on Throughput Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, (sum((avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}[$__range]) * $throughput_unit_rate)) by (chargecode)/scalar(sum((avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}[$__range]) * $throughput_unit_rate))))) * 100"
    }
   ]
  },
  {
   "title": "Top 5 Chargecode based on Partition Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, ((count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode)) * $partition_unit_rate / scalar(count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) * $partition_unit_rate))) * 100"
    }
   ]
  },
  {
   "title": "Top 5 Chargecode based on Storage Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, ((sum(kafka_log_log_size{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode)) * $storage_unit_rate / scalar(sum(kafka_log_log_size{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) * $storage_unit_rate))) * 100"
    }
   ]
  }
 ]
}