{
 "title": "Resource Usage Model Dashboard",
 "tags": [ "model: resource" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "throughput_unit_rate", "query": 0.1 },
   { "name": "partition_unit_rate", "query": 0.05 },
   { "name": "storage_unit_rate", "query": 0.001 },
   { "name": "throughput_in_unit_rate", "query": 0.15 },
   { "name": "throughput_out_unit_rate", "query": 0.05 },
   { "name": "throughput_tps", "query": 1000 },
   { "name": "storage", "query": 100000000 },
   { "name": "partitions_max", "query": 1000 },
   { "name": "total_costs", "query": 5000 },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "chargecode",
    "label": "Chargecode",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_bytesinpersec{cluster=\"${cluster}\"},chargecode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$total_costs", "type": "math" }
   ]
  },
  {
   "title": "Total Resource Usage Bill",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$dash_throughput_bill + $dash_partitions_bill + $dash_storage_bill",
     "type": "math"
    }
   ]
  },
  {
   "title": "Profit/Loss Value",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($dash_throughput_bill + $dash_partitions_bill + $dash_storage_bill) - $total_costs",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(($throughput_utilization + $partition_utilization + $storage_utilization) / 3) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Chargecode Wise Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Chargecode Wise Usage - Resource Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode)) * $throughput_unit_rate + (count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $partition_unit_rate + (sum(kafka_log_log_size{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $storage_unit_rate"
    }
   ]
  },
  {
   "title": "Chargecode Wise Usage - Resource Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode!=\"\"}[$__range])) by (chargecode)) * $throughput_unit_rate + (count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $partition_unit_rate + (sum(kafka_log_log_size{cluster=\"$cluster\",chargecode!=\"\"}) by (chargecode)) * $storage_unit_rate"
    }
   ]
  },
  {
   "title": "Top 5 Chargecode based on Throughput",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, sum((avg_over_time(broker_throughput_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}[$__range]) * $throughput_unit_rate)) by (chargecode))"
    }
   ]
  },
  {
   "title": "Top 5 Chargecode based on Partitions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode) * $partition_unit_rate)"
    }
   ]
  },
  {
   "title": "Top 5 Chargecode based on Storage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, sum(kafka_log_log_size{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode) * $storage_unit_rate)"
    }
   ]
  },
  { "title": "Resource Usage Based", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Throughput Usage Bill",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(broker_throughput_rate{cluster=\"$cluster\", chargecode=~\"$chargecode\"}[$__range])) by (chargecode)) * $throughput_unit_rate"
    }
   ]
  },
  {
   "title": "Throughput Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(broker_throughput_rate{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode)"
    }
   ]
  },
  {
   "title": "Storage Usage Bill",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(kafka_log_log_size{cluster=\"$cluster\", chargecode=~\"$chargecode\"}) by (chargecode)) * $storage_unit_rate"
    }
   ]
  },
  {
   "title": "Storage Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode)"
    }
   ]
  },
  {
   "title": "Partition Usage Bill",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(count(kafka_cluster_partition_replicascount{cluster=\"$cluster\", chargecode=~\"$chargecode\"}) by (chargecode)) * $partition_unit_rate"
    }
   ]
  },
  {
   "title": "Partition Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kafka_cluster_partition_replicascount{cluster=\"$cluster\",chargecode=~\"$chargecode\"}) by (chargecode)"
    }
   ]
  }
 ]
}